(define (problem bw-large-bs)
  (:domain simple-blocks)
  (:objects blocka blockb blockc blockd blocke blockf blockg blockh blocki
	    blockj blockk)
  (:init (on blocka table)
	 (on blockb blocka)
	 (on blockc blockb)
	 (clear blockc)
	 (on blockd table)
	 (on blocke blockd)
	 (on blockj blocke)
	 (on blockk blockj)
	 (clear blockk)
	 (on blockf table)
	 (on blockg blockf)
	 (on blockh blockg)
	 (on blocki blockh)
	 (clear blocki))
  (:goal (and (on blocke blockj)
	      (on blocka blocke)
	      (on blocki blockd)
	      (on blockh blocki)
	      (on blockc blockk)
	      (on blockk blockg)
	      (on blockb blockc))))
