(define (problem log-b)
  (:domain logistics-strips)
  (:objects package1 package2 package3 package5 package7 airplane1 airplane2
	    pgh bos la ny pgh-truck bos-truck la-truck ny-truck bos-po la-po
	    pgh-po ny-po bos-airport pgh-airport la-airport ny-airport)
  (:init (obj package1)
	 (obj package2)
	 (obj package3)
	 (obj package5)
	 (obj package7)
	 (airplane airplane1)
	 (airplane airplane2)
	 (city pgh)
	 (city bos)
	 (city la)
	 (city ny)
	 (truck pgh-truck)
	 (truck bos-truck)
	 (truck la-truck)
	 (truck ny-truck)
	 (location bos-po)
	 (location la-po)
	 (location pgh-po)
	 (location ny-po)
	 (airport bos-airport)
	 (location bos-airport)
	 (airport pgh-airport)
	 (location pgh-airport)
	 (airport la-airport)
	 (location la-airport)
	 (airport ny-airport)
	 (location ny-airport)
	 (in-city pgh-po pgh)
	 (in-city pgh-airport pgh)
	 (in-city bos-po bos)
	 (in-city bos-airport bos)
	 (in-city la-po la)
	 (in-city la-airport la)
	 (in-city ny-po ny)
	 (in-city ny-airport ny)
	 (at package1 pgh-po)
	 (at package2 pgh-po)
	 (at package3 pgh-po)
	 (at package5 bos-po)
	 (at package7 ny-po)
	 (at airplane1 pgh-airport)
	 (at airplane2 pgh-airport)
	 (at bos-truck bos-po)
	 (at pgh-truck pgh-po)
	 (at la-truck la-po)
	 (at ny-truck ny-po))
  (:goal (and (at package1 bos-po) (at package2 ny-po) (at package3 la-po)
	      (at package5 pgh-po) (at package7 pgh-po))))
