(define (problem log-d)
  (:domain logistics-strips)
  (:objects package1 package2 package3 package4 package5 package6 package7
	    package8 package9 airplane1 airplane2 pgh bos la ny sf pgh-truck
	    bos-truck la-truck ny-truck sf-truck bos-po la-po pgh-po ny-po
	    sf-po bos-central la-central pgh-central ny-central sf-central
	    bos-airport pgh-airport la-airport ny-airport sf-airport)
  (:init (obj package1)
	 (obj package2)
	 (obj package3)
	 (obj package4)
	 (obj package5)
	 (obj package6)
	 (obj package7)
	 (obj package8)
	 (obj package9)
	 (airplane airplane1)
	 (airplane airplane2)
	 (city pgh)
	 (city bos)
	 (city la)
	 (city ny)
	 (city sf)
	 (truck pgh-truck)
	 (truck bos-truck)
	 (truck la-truck)
	 (truck ny-truck)
	 (truck sf-truck)
	 (location bos-po)
	 (location la-po)
	 (location pgh-po)
	 (location ny-po)
	 (location sf-po)
	 (location bos-central)
	 (location la-central)
	 (location pgh-central)
	 (location ny-central)
	 (location sf-central)
	 (airport bos-airport)
	 (location bos-airport)
	 (airport pgh-airport)
	 (location pgh-airport)
	 (airport la-airport)
	 (location la-airport)
	 (airport ny-airport)
	 (location ny-airport)
	 (airport sf-airport)
	 (location sf-airport)
	 (in-city pgh-po pgh)
	 (in-city pgh-airport pgh)
	 (in-city pgh-central pgh)
	 (in-city bos-po bos)
	 (in-city bos-airport bos)
	 (in-city bos-central bos)
	 (in-city la-po la)
	 (in-city la-airport la)
	 (in-city la-central la)
	 (in-city ny-po ny)
	 (in-city ny-airport ny)
	 (in-city ny-central ny)
	 (in-city sf-po sf)
	 (in-city sf-airport sf)
	 (in-city sf-central sf)
	 (at package1 pgh-po)
	 (at package2 pgh-central)
	 (at package3 pgh-central)
	 (at package4 ny-po)
	 (at package5 bos-po)
	 (at package6 bos-po)
	 (at package7 ny-po)
	 (at package8 sf-airport)
	 (at package9 sf-central)
	 (at airplane1 pgh-airport)
	 (at airplane2 pgh-airport)
	 (at bos-truck bos-po)
	 (at pgh-truck pgh-airport)
	 (at la-truck la-po)
	 (at ny-truck ny-central)
	 (at sf-truck sf-airport))
  (:goal (and (at package1 bos-po) (at package2 ny-po) (at package3 la-central)
	      (at package4 la-airport) (at package5 pgh-po)
	      (at package6 ny-central) (at package7 pgh-po)
	      (at package8 ny-central) (at package9 sf-po))))
