(define (problem rocket-ext-b)
  (:domain rockets)
  (:objects london paris jfk bos r1 r2 mxf avrim alex jason pencil paper april
	    michelle betty lisa)
  (:init (place london) 
	 (place paris) 
	 (place jfk) 
	 (place bos) 
	 (rocket r1) 
	 (rocket r2) 
	 (cargo mxf) 
	 (cargo avrim) 
	 (cargo alex) 
	 (cargo jason) 
	 (cargo pencil) 
	 (cargo paper) 
	 (cargo april) 
	 (cargo michelle) 
	 (cargo betty) 
	 (cargo lisa) 
	 (at r1 jfk)
	 (at r2 paris)
	 (has-fuel r1)
	 (has-fuel r2)
	 (at mxf jfk)
	 (at avrim paris)
	 (at alex bos)
	 (at jason jfk)
	 (at pencil paris)
	 (at paper london)
	 (at michelle bos)
	 (at april paris)
	 (at betty london)
	 (at lisa london))
  (:goal (and (at mxf bos) (at avrim jfk) (at pencil bos) (at alex jfk)
	      (at april bos) (at lisa paris) (at michelle jfk) (at jason bos)
	      (at paper paris) (at betty jfk))))
