#! /bin/sh
#
# Emulates the version of VHPOP used at the 3rd International Planning
# Competition.
#
# Invocation: ./ipc3-vhpop <domain> <problem>
#

domain=$1
problem=$2

h='-h ADDR/ADDR_WORK/BUC/LIFO'
if (test -z "`grep ':durative-actions' $domain`") then
    f='-f {n,s}LR/{l}MW_add -l 10000 -f {n,s}LR/{u}MW_add/{l}MW_add -l 100000 -f {n,s,l}LR -l 200000 -f {n,s,u}LR/{l}LR -l unlimited'
else
    f='-f {n,s}LR/{l}MW_add -l 12000 -f {n,s}LR/{u}MW_add/{l}MW_add -l 100000 -f {n,s,l}LR -l 240000 -f {n,s,u}LR/{l}LR -l unlimited'
fi

exec ./vhpop -g $h $f $domain $problem
