
#line 2 "tokens.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[461] =
    {   0,
        0,    0,   66,   64,   62,   63,   58,   64,   57,   64,
       64,   64,   64,   64,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   62,   57,    0,
       57,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   61,   59,
       60,   56,   56,   54,   54,   54,   46,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   42,
       54,   54,   54,   54,   54,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   56,

       56,   50,   41,   54,   54,   54,   49,   54,   54,   54,
       54,   54,   40,   54,   54,   54,   54,   54,   54,   54,
        0,   19,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   56,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   47,   54,   54,   54,   39,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   34,   33,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   56,   54,   54,
       54,   54,   54,   43,   54,   54,   54,   54,   54,   48,

       54,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    5,    0,    0,   56,    1,    2,   38,
       44,   45,   54,   54,   36,   37,   54,   54,   24,    0,
        0,    0,    0,   31,    0,   30,    0,    0,    0,    0,
       35,    0,    0,    0,    0,    0,    0,    0,    9,    0,
       10,    0,   56,   54,   54,    3,   54,    0,    0,    0,
        0,    0,    0,    0,    0,   18,    0,    0,   32,    0,
        0,    0,    0,    0,    0,    0,   56,   52,   51,   54,
        0,    0,    0,    0,   27,    0,   13,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   55,   54,   29,
        6,    0,    0,    0,    0,    0,    8,    0,    0,    0,
        0,    0,    0,    0,    0,   53,    0,    0,    0,    0,
        0,    0,    0,   26,    0,    7,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   28,
        0,    4,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   25,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   20,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   22,    0,    0,    0,    0,    0,
        0,    0,   17,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   21,    0,
        0,    0,    0,    0,    0,    0,   11,    0,   23,    0,
        0,    0,    0,   15,    0,    0,   16,   12,   14,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    4,    4,    1,    5,    6,    4,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    9,   10,
       11,   12,   13,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
        1,    1,    1,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   24,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    1,    1,    2,    1,    2,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    2,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[465] =
    {   0,
        0,    0,  899,  930,  896,  930,  930,  844,   60,   54,
      815,  776,  766,   52,   90,    0,   74,   67,   51,   92,
      107,   97,  111,   93,   99,  105,  106,  726,  699,  692,
       71,  118,  109,  142,  136,  135,  111,  118,  122,  129,
      137,  163,  141,  160,  147,  159,  156,  441,  930,  930,
      930,    0,  150,    0,  160,  170,    0,  169,  164,  160,
      181,  178,  172,  178,  175,  186,  184,  192,  198,    0,
      204,  196,  212,  195,  212,  199,  209,  208,  204,  211,
      209,  222,  211,  220,  212,  220,  237,  230,  222,  236,
      236,  233,  247,  253,  240,  243,  249,  247,  255,    0,

      249,    0,    0,  260,  270,  264,    0,  255,  274,  266,
      267,  271,    0,  280,  279,  268,  288,  274,  293,  283,
      286,  930,  306,  291,  304,  305,  303,  312,  296,  311,
      316,  312,  307,  311,  319,  325,  330,  335,  320,  315,
      333,  339,  340,  326,  353,  342,  350,  356,  343,  352,
      342,  355,  357,  368,  372,    0,  365,  358,  367,    0,
      365,  374,  365,  378,  370,  383,  375,  394,  387,  381,
      393,  388,  930,  930,  400,  392,  410,  402,  401,  409,
      400,  413,  410,  419,  409,  415,  425,  412,  430,  423,
      421,  424,  432,    0,  438,  439,  433,  433,  451,    0,

      406,  445,  440,  460,  450,  452,  453,  459,  451,  463,
      468,  456,  469,  477,  472,  464,  477,  473,  486,  482,
      476,  477,  392,  930,  491,  483,  494,    0,    0,    0,
        0,    0,  480,  485,    0,    0,  499,  494,  930,  495,
      501,  496,  516,  930,  506,  930,  503,  510,  507,  514,
      930,  511,  515,  515,  532,  538,  536,  539,  930,  536,
      930,  529,  536,  548,  551,    0,  548,  547,  544,  550,
      547,  554,  553,  545,  553,  930,  561,  571,  930,  573,
      570,  561,  573,  573,  573,  588,  578,    0,    0,  582,
      583,  579,  579,  593,  322,  293,  930,  595,  589,  226,

      592,  591,  609,  610,  612,  610,  610,    0,  615,  624,
      930,  608,  606,  621,  631,  632,  930,  619,  619,  630,
      624,  636,  631,  629,  184,    0,  638,  133,  646,  641,
      653,  646,  644,  930,  648,  930,  131,  645,  659,  654,
      117,  667,   88,  668,  657,   86,  669,  665,  664,  663,
      684,  669,  685,  686,  678,  680,  689,  686,  701,  930,
      689,  930,  697,  705,  705,  708,  698,  697,  706,  704,
      709,  721,   85,  724,  723,  725,  727,  733,  722,  734,
      729,  737,  733,  731,  744,  748,  749,  743,  739,  757,
      759,  750,  759,  756,  770,  755,  762,  771,  930,  767,

      774,  771,  766,  784,  772,  774,  780,  777,  784,  779,
      785,  797,  795,  787,  930,  805,  804,  810,  808,  812,
      808,  807,  930,  813,  823,  821,  818,  814,  834,  828,
      819,  823,  823,  831,  837,  838,  836,  838,  930,  845,
      837,  843,  842,  849,  851,  852,  930,  856,  930,  853,
      861,  864,  860,  930,  861,  864,  930,  930,  930,  930,
      922,   72,  924,  926
    } ;

static const flex_int16_t yy_def[465] =
    {   0,
      460,    1,  460,  460,  460,  460,  460,  460,  460,  460,
      461,  460,  460,  462,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  461,  460,  460,
      460,  464,  464,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  464,

      464,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  464,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  464,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  464,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  464,  463,  463,  463,  463,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  464,  463,  463,  463,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,

      460,  460,  460,  460,  460,  460,  460,  464,  463,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  463,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,

      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,    0,
      460,  460,  460,  460
    } ;

static const flex_int16_t yy_nxt[996] =
    {   0,
        4,    5,    6,    7,    7,    8,    9,   10,   11,   12,
        7,   13,   14,   15,   16,   16,   17,   18,   19,   16,
       16,   20,   16,   16,   16,   21,   22,   23,   24,   16,
       16,   25,   26,   16,   16,   27,   16,   16,   16,    4,
       15,   16,   16,   17,   18,   19,   16,   16,   20,   16,
       16,   21,   22,   23,   24,   16,   16,   25,   26,   16,
       16,   27,   16,   16,   16,   30,   31,   32,   53,   33,
       34,   35,   36,   37,   52,   38,   30,   31,   63,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   60,  383,
      358,   58,  355,   61,   32,   53,   33,   34,   35,   36,

       37,   59,   38,   62,   63,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   55,   60,   56,   64,   58,   61,
       65,  353,   57,   72,   67,   69,   75,   59,   66,   62,
       68,   73,   74,   76,   77,  349,   78,  342,   87,   89,
       55,   70,   56,   64,   88,   71,   90,   65,   57,   72,
       67,   91,   69,   75,   82,   66,   68,   73,   74,   85,
       76,   77,   78,   79,   87,   83,   89,   70,   86,   80,
       88,   71,   84,   90,   94,   81,   92,   95,   91,   96,
       97,   82,   99,  101,  102,   85,  103,  104,  340,  105,
       79,   83,  106,   93,   86,   80,   98,  107,   84,  108,

       94,   81,  109,   92,   95,   96,  110,   97,   99,  101,
      102,  111,  112,  103,  104,  105,  113,  114,  106,   93,
      115,  116,   98,  117,  107,  118,  108,  119,  109,  120,
      318,  121,  110,  122,  123,  124,  125,  111,  112,  126,
      127,  129,  113,  114,  128,  130,  131,  115,  116,  117,
      132,  133,  118,  119,  134,  135,  120,  121,  136,  122,
      123,  124,  125,  137,  138,  126,  139,  127,  129,  140,
      128,  130,  131,  141,  142,  143,  144,  132,  133,  145,
      134,  146,  135,  147,  148,  136,  149,  150,  152,  137,
      151,  138,  153,  139,  154,  140,  155,  315,  156,  141,

      142,  143,  157,  144,  158,  145,  159,  161,  146,  160,
      147,  148,  149,  165,  150,  152,  151,  166,  167,  153,
      168,  154,  162,  155,  156,  169,  314,  170,  171,  157,
      158,  172,  176,  159,  161,  160,  173,  163,  164,  174,
      165,  175,  177,  178,  166,  167,  181,  168,  182,  162,
      179,  180,  169,  170,  183,  171,  184,  185,  172,  176,
      187,  186,  173,  163,  164,  174,  188,  175,  189,  177,
      178,  190,  181,  191,  182,  192,  193,  179,  180,  194,
      195,  183,  196,  184,  185,  197,  187,  198,  186,  199,
      200,  201,  202,  188,  189,  203,  260,  204,  190,  205,

      191,  192,  193,  206,  207,  194,  195,  208,  196,  209,
      238,  210,  197,  211,  198,  199,  200,  201,  202,  212,
      213,  214,  203,  204,  215,  216,  205,  217,  218,  206,
      219,  207,  220,  208,  221,  223,  209,  210,  222,  211,
      224,  225,  226,   49,  227,  212,  213,  228,  214,  229,
      215,  230,  216,  217,  218,  231,  232,  219,  220,  233,
      234,  221,  223,  235,  222,  236,  224,  225,  237,  226,
      227,  239,  240,  241,  228,  229,  242,  230,  243,  244,
      245,  231,  232,  246,  247,  248,  233,  234,  249,  235,
      250,  236,  251,  252,  254,  237,  253,  239,  240,  255,

      241,  256,  242,  257,  243,  244,  258,  245,  259,  246,
      261,  247,  248,  262,  249,  263,  268,  250,  264,  251,
      252,  254,  253,  265,  266,  255,  267,  269,  256,  270,
      257,  271,  258,  272,  259,  274,  275,  261,  276,  262,
      273,  277,  263,  268,  264,  278,  279,  280,  281,  265,
      266,  282,  267,  269,  283,  270,  284,  285,  271,  272,
      286,  274,  275,  287,  276,  288,  273,  277,  289,  290,
      296,  278,  279,  280,  291,  281,  292,  293,  282,  294,
      295,  283,  297,  284,  285,  298,  286,  299,  300,  287,
      301,  302,  288,  303,  304,  289,  290,  296,  305,  306,

      291,  307,  292,  293,  308,  294,  295,  309,  297,  310,
      311,  298,  312,  299,  313,  300,  316,  301,  302,  303,
      317,  304,  319,  320,  305,  306,  321,  322,  307,  323,
      308,  324,  326,  309,  325,  310,  311,  327,  312,  328,
      329,  313,  330,  316,  331,  332,  317,  333,  319,  320,
      334,  335,  337,  321,  322,  336,  323,  338,  324,  326,
      325,  339,  341,  343,  327,  328,  329,  344,  345,  330,
      346,  331,  332,  333,  347,  348,  334,  350,  335,  337,
      351,  336,  352,  338,  354,  356,  359,  339,  341,  357,
      343,  360,  361,  344,  362,  345,  346,  363,   29,  364,

      347,  348,  365,  350,  366,   29,  367,  351,  352,  368,
      369,  354,  356,  359,  370,  357,  371,  360,  361,  372,
      362,  373,  374,  375,  363,  364,  376,   28,  377,  365,
      378,  366,  367,  379,  380,  368,  381,  369,  382,  384,
      370,  385,  386,  371,  387,  372,  388,  373,  389,  374,
      375,  390,  392,  376,  377,  391,  378,  393,  394,  379,
      380,  395,  381,  396,  397,  382,  384,  398,  385,  386,
      399,  387,  400,  388,  389,  401,   51,  402,  390,  392,
      403,  391,  404,  393,  394,  405,   50,  406,  395,  407,
      396,  397,  408,  398,  409,  410,  399,  411,  412,  400,

      413,  420,  401,  402,  414,  415,  416,  403,  404,  417,
      418,  419,  405,  406,  421,  407,  422,   49,  423,  408,
      409,  424,  410,  411,  412,  425,  426,  413,  420,  427,
      414,  415,  416,  428,  431,  417,  418,  419,  429,  430,
      432,  421,  433,  422,  423,  434,  435,  436,  424,  437,
       29,  438,  425,  426,  439,  440,  427,  441,  442,  445,
      428,  431,  443,  444,  429,  430,  446,  432,  447,  433,
      448,  434,  435,  449,  436,  450,  437,  438,  451,  452,
      439,  440,  453,  441,  454,  442,  445,  455,  443,  444,
      456,  457,  458,  446,  447,  459,  448,   28,  460,  449,

      460,  450,  460,  460,  451,  452,  460,  460,  453,  460,
      454,  460,  460,  455,  460,  460,  456,  457,  458,  460,
      460,  459,   48,   48,   48,   54,   54,  100,  100,    3,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460

    } ;

static const flex_int16_t yy_chk[996] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    9,    9,   10,   14,   10,
       10,   10,   10,   10,  462,   10,   31,   31,   19,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   18,  373,
      346,   17,  343,   18,   10,   14,   10,   10,   10,   10,

       10,   17,   10,   18,   19,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   15,   18,   15,   20,   17,   18,
       21,  341,   15,   24,   22,   23,   27,   17,   21,   18,
       22,   25,   26,   32,   32,  337,   33,  328,   37,   39,
       15,   23,   15,   20,   38,   23,   40,   21,   15,   24,
       22,   41,   23,   27,   35,   21,   22,   25,   26,   36,
       32,   32,   33,   34,   37,   35,   39,   23,   36,   34,
       38,   23,   35,   40,   43,   34,   42,   44,   41,   45,
       46,   35,   47,   53,   55,   36,   56,   58,  325,   59,
       34,   35,   60,   42,   36,   34,   46,   61,   35,   62,

       43,   34,   63,   42,   44,   45,   64,   46,   47,   53,
       55,   65,   66,   56,   58,   59,   67,   68,   60,   42,
       69,   71,   46,   72,   61,   73,   62,   74,   63,   75,
      300,   76,   64,   77,   78,   79,   80,   65,   66,   81,
       82,   84,   67,   68,   83,   85,   86,   69,   71,   72,
       87,   88,   73,   74,   89,   90,   75,   76,   91,   77,
       78,   79,   80,   92,   93,   81,   94,   82,   84,   95,
       83,   85,   86,   96,   97,   98,   99,   87,   88,  101,
       89,  104,   90,  105,  106,   91,  108,  109,  111,   92,
      110,   93,  112,   94,  114,   95,  115,  296,  116,   96,

       97,   98,  117,   99,  118,  101,  119,  121,  104,  120,
      105,  106,  108,  124,  109,  111,  110,  125,  126,  112,
      127,  114,  123,  115,  116,  128,  295,  129,  130,  117,
      118,  131,  135,  119,  121,  120,  132,  123,  123,  133,
      124,  134,  136,  137,  125,  126,  139,  127,  140,  123,
      138,  138,  128,  129,  141,  130,  142,  143,  131,  135,
      144,  143,  132,  123,  123,  133,  145,  134,  146,  136,
      137,  147,  139,  148,  140,  149,  150,  138,  138,  151,
      152,  141,  153,  142,  143,  154,  144,  155,  143,  157,
      158,  159,  161,  145,  146,  162,  223,  163,  147,  164,

      148,  149,  150,  165,  166,  151,  152,  167,  153,  168,
      201,  169,  154,  170,  155,  157,  158,  159,  161,  171,
      172,  175,  162,  163,  176,  177,  164,  178,  179,  165,
      180,  166,  181,  167,  182,  184,  168,  169,  183,  170,
      185,  186,  187,   48,  188,  171,  172,  189,  175,  190,
      176,  191,  177,  178,  179,  192,  193,  180,  181,  195,
      196,  182,  184,  197,  183,  198,  185,  186,  199,  187,
      188,  202,  203,  204,  189,  190,  205,  191,  206,  207,
      208,  192,  193,  209,  210,  211,  195,  196,  212,  197,
      213,  198,  214,  215,  217,  199,  216,  202,  203,  218,

      204,  219,  205,  220,  206,  207,  221,  208,  222,  209,
      225,  210,  211,  226,  212,  227,  240,  213,  233,  214,
      215,  217,  216,  234,  237,  218,  238,  241,  219,  242,
      220,  243,  221,  245,  222,  247,  248,  225,  249,  226,
      245,  250,  227,  240,  233,  252,  253,  254,  255,  234,
      237,  256,  238,  241,  257,  242,  258,  260,  243,  245,
      262,  247,  248,  263,  249,  264,  245,  250,  265,  267,
      273,  252,  253,  254,  268,  255,  269,  270,  256,  271,
      272,  257,  274,  258,  260,  275,  262,  277,  278,  263,
      280,  281,  264,  282,  283,  265,  267,  273,  284,  285,

      268,  286,  269,  270,  287,  271,  272,  290,  274,  291,
      292,  275,  293,  277,  294,  278,  298,  280,  281,  282,
      299,  283,  301,  302,  284,  285,  303,  304,  286,  305,
      287,  306,  309,  290,  307,  291,  292,  310,  293,  312,
      313,  294,  314,  298,  315,  316,  299,  318,  301,  302,
      319,  320,  322,  303,  304,  321,  305,  323,  306,  309,
      307,  324,  327,  329,  310,  312,  313,  330,  331,  314,
      332,  315,  316,  318,  333,  335,  319,  338,  320,  322,
      339,  321,  340,  323,  342,  344,  347,  324,  327,  345,
      329,  348,  349,  330,  350,  331,  332,  351,   30,  352,

      333,  335,  353,  338,  354,   29,  355,  339,  340,  356,
      357,  342,  344,  347,  358,  345,  359,  348,  349,  361,
      350,  363,  364,  365,  351,  352,  366,   28,  367,  353,
      368,  354,  355,  369,  370,  356,  371,  357,  372,  374,
      358,  375,  376,  359,  377,  361,  378,  363,  379,  364,
      365,  380,  382,  366,  367,  381,  368,  383,  384,  369,
      370,  385,  371,  386,  387,  372,  374,  388,  375,  376,
      389,  377,  390,  378,  379,  391,   13,  392,  380,  382,
      393,  381,  394,  383,  384,  395,   12,  396,  385,  397,
      386,  387,  398,  388,  400,  401,  389,  402,  403,  390,

      404,  411,  391,  392,  405,  406,  407,  393,  394,  408,
      409,  410,  395,  396,  412,  397,  413,   11,  414,  398,
      400,  416,  401,  402,  403,  417,  418,  404,  411,  419,
      405,  406,  407,  420,  424,  408,  409,  410,  421,  422,
      425,  412,  426,  413,  414,  427,  428,  429,  416,  430,
        8,  431,  417,  418,  432,  433,  419,  434,  435,  438,
      420,  424,  436,  437,  421,  422,  440,  425,  441,  426,
      442,  427,  428,  443,  429,  444,  430,  431,  445,  446,
      432,  433,  448,  434,  450,  435,  438,  451,  436,  437,
      452,  453,  455,  440,  441,  456,  442,    5,    3,  443,

        0,  444,    0,    0,  445,  446,    0,    0,  448,    0,
      450,    0,    0,  451,    0,    0,  452,  453,  455,    0,
        0,  456,  461,  461,  461,  463,  463,  464,  464,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokens.ll"
/* -*-C++-*-
 * Copyright (C) 2002--2005 Carnegie Mellon University
 * Copyright (C) 2019 Google Inc
 *
 * This file is part of VHPOP.
 *
 * VHPOP is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * VHPOP is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with VHPOP; if not, write to the Free Software Foundation,
 * Inc., #59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * PDDL tokenizer.
 */
#line 24 "tokens.ll"
struct Condition;
struct Formula;
struct Literal;
struct Atom;
struct Expression;
struct Fluent;

#include "terms.h"
#include "types.h"

#include <cctype>
#include <set>
#include <string>
#include <vector>
#include "pddl.h"


/* Current line number. */
size_t line_number;

/* Allocates a string containing the lowercase characters of the given
   C string, and returns the given token. */
static int make_string(const char* s, int token);
/* Makes a number of the given string, and return the NUMBER token. */
static int make_number(const char* s);

#line 865 "tokens.cc"
#line 866 "tokens.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 56 "tokens.ll"


#line 1084 "tokens.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 461 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 460 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 58 "tokens.ll"
return make_string(yytext, DEFINE);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 59 "tokens.ll"
return make_string(yytext, DOMAIN_TOKEN);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 60 "tokens.ll"
return make_string(yytext, PROBLEM);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 61 "tokens.ll"
return REQUIREMENTS;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 62 "tokens.ll"
return TYPES;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 63 "tokens.ll"
return CONSTANTS;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 64 "tokens.ll"
return PREDICATES;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "tokens.ll"
return FUNCTIONS;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 66 "tokens.ll"
return STRIPS;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "tokens.ll"
return TYPING;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "tokens.ll"
return NEGATIVE_PRECONDITIONS;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 69 "tokens.ll"
return DISJUNCTIVE_PRECONDITIONS;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 70 "tokens.ll"
return EQUALITY;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 71 "tokens.ll"
return EXISTENTIAL_PRECONDITIONS;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 72 "tokens.ll"
return UNIVERSAL_PRECONDITIONS;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 73 "tokens.ll"
return QUANTIFIED_PRECONDITIONS;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 74 "tokens.ll"
return CONDITIONAL_EFFECTS;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 75 "tokens.ll"
return FLUENTS;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 76 "tokens.ll"
return ADL;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 77 "tokens.ll"
return DURATIVE_ACTIONS;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 78 "tokens.ll"
return DURATION_INEQUALITIES;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 79 "tokens.ll"
return CONTINUOUS_EFFECTS;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 80 "tokens.ll"
return TIMED_INITIAL_LITERALS;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 81 "tokens.ll"
return ACTION;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 82 "tokens.ll"
return DURATIVE_ACTION;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 83 "tokens.ll"
return PARAMETERS;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 84 "tokens.ll"
return DURATION;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 85 "tokens.ll"
return PRECONDITION;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 86 "tokens.ll"
return CONDITION;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 87 "tokens.ll"
return EFFECT;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 88 "tokens.ll"
return PDOMAIN;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 89 "tokens.ll"
return OBJECTS;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 90 "tokens.ll"
return INIT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 91 "tokens.ll"
return GOAL;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 92 "tokens.ll"
return METRIC;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 93 "tokens.ll"
return make_string(yytext, NUMBER_TOKEN);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 94 "tokens.ll"
return make_string(yytext, OBJECT_TOKEN);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 95 "tokens.ll"
return make_string(yytext, EITHER);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 96 "tokens.ll"
return make_string(yytext, WHEN);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 97 "tokens.ll"
return make_string(yytext, NOT);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 98 "tokens.ll"
return make_string(yytext, AND);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 99 "tokens.ll"
return make_string(yytext, OR);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 100 "tokens.ll"
return make_string(yytext, IMPLY);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 101 "tokens.ll"
return make_string(yytext, EXISTS);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 102 "tokens.ll"
return make_string(yytext, FORALL);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 103 "tokens.ll"
return make_string(yytext, AT);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 104 "tokens.ll"
return make_string(yytext, OVER);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 105 "tokens.ll"
return make_string(yytext, START);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 106 "tokens.ll"
return make_string(yytext, END);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 107 "tokens.ll"
return make_string(yytext, ALL);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 108 "tokens.ll"
return make_string(yytext, MINIMIZE);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 109 "tokens.ll"
return make_string(yytext, MAXIMIZE);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 110 "tokens.ll"
return make_string(yytext, TOTAL_TIME);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 111 "tokens.ll"
return make_string(yytext, NAME);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 112 "tokens.ll"
return make_string(yytext, DURATION_VAR);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 113 "tokens.ll"
return make_string(yytext, VARIABLE);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 "tokens.ll"
return make_number(yytext);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 115 "tokens.ll"
return yytext[0];
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 116 "tokens.ll"
return LE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 117 "tokens.ll"
return GE;
	YY_BREAK
case 61:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 118 "tokens.ll"
/* comment */
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 119 "tokens.ll"
/* whitespace */
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 120 "tokens.ll"
line_number++;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 121 "tokens.ll"
return ILLEGAL_TOKEN;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 123 "tokens.ll"
ECHO;
	YY_BREAK
#line 1466 "tokens.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 461 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 461 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 460);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 123 "tokens.ll"


/* Allocates a string containing the lowercase characters of the given
   C string, and returns the given token. */
static int make_string(const char* s, int token) {
  std::string* result = new std::string();
  for (const char* p = s; *p != '\0'; p++) {
    *result += tolower(*p);
  }
  yylval.str = result;
  return token;
}


/* Makes a number of the given string, and return the NUMBER token. */
static int make_number(const char* s) {
  yylval.num = atof(s);
  return NUMBER;
}

