(define (problem bw-large-ds)
  (:domain simple-blocks)
  (:objects blocka blockb blockc blockd blocke blockf blockg blockh blocki
	    blockj blockk blockl blockm blockn blocko blockp blockq blockr
	    blocks)
  (:init (on blockm table)
	 (on blockl blockm)
	 (on blocka blockl)
	 (clear blocka)
	 (on blocko table)
	 (on blockn blocko)
	 (on blockd blockn)
	 (on blocke blockd)
	 (on blockj blocke)
	 (on blockk blockj)
	 (clear blockk)
	 (on blockf table)
	 (on blockg blockf)
	 (on blockh blockg)
	 (on blocki blockh)
	 (clear blocki)
	 (on blockb table)
	 (on blockc blockb)
	 (on blockp blockc)
	 (on blockq blockp)
	 (on blockr blockq)
	 (on blocks blockr)
	 (clear blocks))
  (:goal (and (on blocke blockj)
	      (on blocka blocke)
	      (on blockn blocka)
	      (on blocks blockn)
	      (on blockr blocks)
	      (on blockq blockr)
	      (on blocki blockd)
	      (on blockh blocki)
	      (on blockm blockh)
	      (on blocko blockm)
	      (on blockk blockg)
	      (on blockp blockk)
	      (on blockc blockp)
	      (on blockb blockc)
	      (on blockl blockb))))
