(define (problem fixit)
  (:domain init-flat-tire)
  (:objects wheel1 wheel2 hub nuts boot)
  (:init (wheel wheel1)
	 (wheel wheel2) (hub hub) (nut nuts)
	 (container boot) (intact wheel2)
	 (in jack boot) (in pump boot)
	 (in wheel2 boot) (in wrench boot)
	 (on wheel1 hub) (on-ground hub) (tight nuts hub))
  (:goal (and (not (open boot)) (in jack boot) (in pump boot)
	      (in wheel1 boot) (in wrench boot)
	      (tight nuts hub) (inflated wheel2) (on wheel2 hub))))
