(define (problem bw-large-cs)
  (:domain simple-blocks)
  (:objects blocka blockb blockc blockd blocke blockf blockg blockh blocki
	    blockj blockk blockl blockm blockn blocko)
  (:init (on blockm table)
	 (on blockl blockm)
	 (on blocka blockl)
	 (on blockb blocka)
	 (on blockc blockb)
	 (clear blockc)
	 (on blocko table)
	 (on blockn blocko)
	 (on blockd blockn)
	 (on blocke blockd)
	 (on blockj blocke)
	 (on blockk blockj)
	 (clear blockk)
	 (on blockf table)
	 (on blockg blockf)
	 (on blockh blockg)
	 (on blocki blockh)
	 (clear blocki))
  (:goal (and (on blocke blockj)
	      (on blocka blocke)
	      (on blockn blocka)
	      (on blocki blockd)
	      (on blockh blocki)
	      (on blockm blockh)
	      (on blocko blockm)
	      (on blockk blockg)
	      (on blockc blockk)
	      (on blockb blockc)
	      (on blockl blockb))))
