(define (problem fix5)
  (:domain init-flat-tire)
  (:objects wheel1 wheel2 hub nuts boot)
  (:init (wheel wheel1)
	 (wheel wheel2) (hub hub) (nut nuts)
	 (container boot)
	 (open boot) (in jack boot) (in pump boot)
	 (in wheel1 boot)
	 (in wrench boot) (inflated wheel2) (on wheel2 hub)
	 (tight nuts hub))
  (:goal (and (not (open boot)) (in jack boot) (in pump boot)
	      (in wheel1 boot)
	      (in wrench boot) (inflated wheel2) (on wheel2 hub)
	      (tight nuts hub))))
