(define (problem log-c)
  (:domain logistics-strips)
  (:objects package1 package2 package3 package4 package5 package6 package7
	    pgh-truck bos-truck la-truck ny-truck airplane1 airplane2
	    bos-po la-po pgh-po ny-po bos-airport pgh-airport la-airport
	    ny-airport pgh bos la ny)
  (:init (obj package1) 
	 (obj package2) 
	 (obj package3) 
	 (obj package4) 
	 (obj package5) 
	 (obj package6) 
	 (obj package7) 
	 (truck pgh-truck) 
	 (truck bos-truck) 
	 (truck la-truck) 
	 (truck ny-truck) 
	 (airplane airplane1) 
	 (airplane airplane2) 
	 (location bos-po) 
	 (location la-po) 
	 (location pgh-po) 
	 (location ny-po) 
	 (airport bos-airport) 
	 (location bos-airport) 
	 (airport pgh-airport) 
	 (location pgh-airport) 
	 (airport la-airport) 
	 (location la-airport) 
	 (airport ny-airport) 
	 (location ny-airport) 
	 (city pgh) 
	 (city bos) 
	 (city la) 
	 (city ny) 
	 (at package1 pgh-po)
	 (at package2 pgh-po)
	 (at package3 pgh-po)
	 (at package4 ny-po)
	 (at package5 bos-po)
	 (at package6 bos-po)
	 (at package7 ny-po)
	 (at airplane1 pgh-airport)
	 (at airplane2 pgh-airport)
	 (at bos-truck bos-po)
	 (at pgh-truck pgh-po)
	 (at la-truck la-po)
	 (at ny-truck ny-po)
	 (in-city pgh-po pgh)
	 (in-city pgh-airport pgh)
	 (in-city bos-po bos)
	 (in-city bos-airport bos)
	 (in-city la-po la)
	 (in-city la-airport la)
	 (in-city ny-po ny)
	 (in-city ny-airport ny))
  (:goal (and (at package1 bos-po) (at package2 ny-po) (at package3 la-po)
	      (at package4 la-airport) (at package5 pgh-po)
	      (at package6 ny-airport) (at package7 pgh-po))))
