(define (problem monkey-test1)
  (:domain monkey-domain)
  (:objects p1 p2 p3 p4)
  (:init (location p1)
	 (location p2) (location p3) (location p4)
	 (at monkey p1) (on-floor) (at box p2) (at bananas p3)
	 (at knife p4))
  (:goal (hasbananas)))
