(define (problem fix3)
  (:domain init-flat-tire)
  (:objects wheel1 wheel2 hub nuts boot)
  (:init (wheel wheel1)
	 (wheel wheel2) (hub hub) (nut nuts)
	 (container boot) (intact wheel2)
	 (have pump) (have wheel2)
	 (have wrench) (on wheel1 hub) (inflated wheel2)
	 (loose nuts hub))
  (:goal (and (tight nuts hub) (on-ground hub)
	      (on wheel2 hub))))
