(define (problem prodigy-p22)
  (:domain prodigy-bw)
  (:objects a b c d e f g)
  (:init (object b)
	 (clear a)
	 (clear b) (on-table b)
	 (object g) (on-table g)
	 (object f) (on f g)
	 (object e) (on e f)
	 (object d) (on d e)
	 (object c) (on c d) (clear c)
	 (object a) (on-table a)
	 (arm-empty))
  (:goal (and (on b c) (on-table a) (on f a) (on c d))))
