(define (problem bw-large-as)
  (:domain simple-blocks)
  (:objects blocka blockb blockc blockd blocke blockf blockg blockh blocki)
  (:init (on blocka table)
	 (on blockb blocka)
	 (on blockc blockb)
	 (clear blockc)
	 (on blockd table)
	 (on blocke blockd)
	 (clear blocke)
	 (on blockf table)
	 (on blockg blockf)
	 (on blockh blockg)
	 (on blocki blockh)
	 (clear blocki))
  (:goal (and (on blocka blocke)
	      (on blocki blockd)
	      (on blockh blocki)
	      (on blockc blockg)
	      (on blockb blockc))))
