(define (problem fixit2)
  (:domain init-flat-tire2)
  (:requirements :disjunctive-preconditions :universal-preconditions)
  (:objects wheel1 wheel2 hub nuts boot)
  (:init (wheel wheel1)
	 (wheel wheel2) (hub hub) (nut nuts)
	 (tool jack) (tool pump) (tool wrench)
	 (container boot) (intact wheel2)
	 (in jack boot) (in pump boot)
	 (in wheel2 boot) (in wrench boot)
	 (on wheel1 hub) (on wheel1 ground) (tight nuts hub))
  (:goal (and (not (open boot))
	      (forall (?x) (imply (tool ?x) (in ?x boot)))
	      (in wheel1 boot)
	      (tight nuts hub) (inflated wheel2)(on wheel2 hub))))
